---
# This workflow integrates qwiet.ai preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 11 * * 6'

jobs:
  NextGen-Static-AnalysisPostBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK v8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
     
    - name: Download QwietAI CLI
      run: |
         curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: preZero Static Analysis
      run: |
         ${GITHUB_WORKSPACE}/sl --version
         QWIET_EXTERNAL_SECRETS=true ${GITHUB_WORKSPACE}/sl analyze --strict --wait \
          --app WebGoatQwietAI \
          --tag branch=${{ github.head_ref }} \
      env:
         SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
         SHIFTLEFT_API_HOST: www.shiftleft.io
         SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
         SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

    - name: Download export.py and requirements.txt
      run: |
        curl -O https://raw.githubusercontent.com/ShiftLeftSecurity/field-integrations/master/shiftleft-utils/export.py
        curl -O https://raw.githubusercontent.com/ShiftLeftSecurity/field-integrations/master/shiftleft-utils/config.py
        curl -O https://raw.githubusercontent.com/ShiftLeftSecurity/field-integrations/master/shiftleft-utils/common.py
        curl -O https://raw.githubusercontent.com/ShiftLeftSecurity/field-integrations/master/shiftleft-utils/requirements.txt
    - name: Verify export.py file exists
      run: |
        ls -la ${GITHUB_WORKSPACE}

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Run export.py and generate SARIF report
      run: |
        #APP_NAME=${{ github.event.repository.name }}
        python3 ${GITHUB_WORKSPACE}/export.py -f sarif -a SECTAB
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    - name: Upload SARIF file to GitHub Security Tab
      uses: github/codeql-action/upload-sarif@v3  # Updated to v3
      with:
        sarif_file: ./ngsast-report-SECTAB.sarif  # Correct dynamic path for SARIF output
